name: linkub-back-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  S3_BUCKET_NAME: linkhub-bucket

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

          # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir deploy

        # Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

         # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

          # script files 복사
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      - name: Make zip file
        run: zip -r ./linkhub.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./linkhub.zip s3://linkhub-bucket

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws deploy create-deployment
            --application-name linkhub
            --deployment-config-name CodeDeployDefault.AllAtOnce
            --deployment-group-name linkhub-deploy-group
            --file-exists-behavior OVERWRITE
            --s3-location bucket=linkhub-bucket,bundleType=zip,key=linkhub.zip

#          aws deploy create-deployment
#            --application-name linkhub
#            --deployment-group-name linkhub-deploy-group
#            --file-exists-behavior OVERWRITE
#            --s3-location bucket=linkhub-bucket,bundleType=zip,key=linkhub.zip
          

